Repository kakao/olive-ui, pull requests merged in 2022-08, with the labels that each got.

#2 build: change deployment setting
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/gh-pages-deploy.yml
  .husky/commit-msg
  angular.json
  commitlint.config.js
  package-lock.json
  package.json
  src/app/app.component.spec.ts
Labels: github_actions

#3 feat: add footer component
  src/@olive/components/footer/footer.component.html
  src/@olive/components/footer/footer.component.ts
  src/@olive/components/footer/footer.module.ts
  src/@olive/components/footer/footer.type.ts
  src/app/layout/basic/basic.component.html
  src/app/layout/basic/basic.module.ts
  src/app/layout/menu/menu.component.html
  src/app/routes/components/box/box.component.html
  src/app/routes/components/components.module.ts
  src/app/routes/components/footer/footer.component.html
  src/app/routes/components/footer/footer.component.ts
  src/app/routes/components/footer/footer.module.ts
  src/styles/olive.scss
Labels: features

#4 chore: update dependencies
  .eslintrc.json
  angular.json
  package-lock.json
  package.json
Labels: dependencies
